# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz/main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 389)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 781, 161))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 25, 141, 16))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(140, 30, 20, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.secilenVeri = QtWidgets.QComboBox(self.groupBox)
        self.secilenVeri.setGeometry(QtCore.QRect(160, 20, 611, 26))
        self.secilenVeri.setObjectName("secilenVeri")
        self.secilenVeri.addItem("")
        self.secilenVeri.addItem("")
        self.secilenVeri.addItem("")
        self.secilenVeri.addItem("")
        self.secilenVeri.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.teksefer = QtWidgets.QRadioButton(self.groupBox)
        self.teksefer.setGeometry(QtCore.QRect(160, 60, 151, 20))
        self.teksefer.setChecked(True)
        self.teksefer.setObjectName("teksefer")
        self.surekli = QtWidgets.QRadioButton(self.groupBox)
        self.surekli.setGeometry(QtCore.QRect(300, 60, 131, 20))
        self.surekli.setObjectName("surekli")
        self.sure = QtWidgets.QTextEdit(self.groupBox)
        self.sure.setEnabled(False)
        self.sure.setGeometry(QtCore.QRect(530, 60, 231, 21))
        self.sure.setObjectName("sure")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(420, 62, 101, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 90, 131, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 120, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 781, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.durdurButon = QtWidgets.QPushButton(self.groupBox_2)
        self.durdurButon.setGeometry(QtCore.QRect(0, 95, 131, 32))
        self.durdurButon.setObjectName("durdurButon")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(130, 25, 20, 101))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 141, 16))
        self.label_3.setObjectName("label_3")
        self.secilenVeri_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.secilenVeri_2.setGeometry(QtCore.QRect(150, 30, 611, 26))
        self.secilenVeri_2.setObjectName("secilenVeri_2")
        self.secilenVeri_2.addItem("")
        self.secilenVeri_2.addItem("")
        self.secilenVeri_2.addItem("")
        self.secilenVeri_2.addItem("")
        self.secilenVeri_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 60, 16))
        self.label_4.setObjectName("label_4")
        self.cikti_label = QtWidgets.QLabel(self.centralwidget)
        self.cikti_label.setGeometry(QtCore.QRect(80, 180, 711, 16))
        self.cikti_label.setText("")
        self.cikti_label.setObjectName("cikti_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.calistir)
        self.teksefer.clicked.connect(MainWindow.teksefer)
        self.surekli.clicked.connect(MainWindow.surekli)
        self.pushButton_2.clicked.connect(MainWindow.tamamini_calistir)
        self.pushButton_3.clicked.connect(MainWindow.log_goster)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Uygulama Adı v1"))
        self.groupBox.setTitle(_translate("MainWindow", "Çalıştırma"))
        self.label.setText(_translate("MainWindow", "Hangisi Çalıştırılsın?"))
        self.secilenVeri.setItemText(0, _translate("MainWindow", "ornek1"))
        self.secilenVeri.setItemText(1, _translate("MainWindow", "ornek2"))
        self.secilenVeri.setItemText(2, _translate("MainWindow", "ornek3"))
        self.secilenVeri.setItemText(3, _translate("MainWindow", "ornek4"))
        self.secilenVeri.setItemText(4, _translate("MainWindow", "ornek5"))
        self.pushButton.setText(_translate("MainWindow", "İşlemi Başlat"))
        self.teksefer.setText(_translate("MainWindow", "Tek Sefer Çalıştır"))
        self.surekli.setText(_translate("MainWindow", "Sürekli Çalıştır"))
        self.label_2.setText(_translate("MainWindow", "Kaç saniyede bir"))
        self.pushButton_2.setText(_translate("MainWindow", "Tümünü Çalıştır"))
        self.pushButton_3.setText(_translate("MainWindow", "Son Logları Göster"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Durdurma"))
        self.durdurButon.setText(_translate("MainWindow", "İşlemi Başlat"))
        self.label_3.setText(_translate("MainWindow", "Hangisi Durdurulsun?"))
        self.secilenVeri_2.setItemText(0, _translate("MainWindow", "ornek1"))
        self.secilenVeri_2.setItemText(1, _translate("MainWindow", "ornek2"))
        self.secilenVeri_2.setItemText(2, _translate("MainWindow", "ornek3"))
        self.secilenVeri_2.setItemText(3, _translate("MainWindow", "ornek4"))
        self.secilenVeri_2.setItemText(4, _translate("MainWindow", "ornek5"))
        self.label_4.setText(_translate("MainWindow", "Durum:"))

